swagger: "2.0"
info:
  description: "This is API spec of cybex.io."
  version: "1.0.0"
  title: "Cybex API"
  termsOfService: "https://www.cybex.io/app/terms"
  contact:
    email: "service@cybex.io"
host: "localhost:8091"
basePath: "/v1"
schemes:
- "https"
paths:
  /refData:
    get:
      tags:
      - refData
      summary: "Get reference data."
      operationId: "refData.get"
      produces:
      - "application/xml"
      - "application/json"
      responses:
        200:
          description: "Request was successful"
          schema:
            type: object

        400:
          description: Parameter Error

        401:
          description: Unauthorized

        404:
          description: Not Found


  /position:
    get:
      tags:
      - Position
      summary: Get user's positions.
      description: Get user's positions.
      operationId: Position.get
      parameters:
      - name: accountName
        in: query
        description: "Account name"
        required: true
        type: string
      responses:
        200:
          description: "Request was successful"
          schema:
            type: array
            items:
              $ref: '#/definitions/Position'
        400:
          description: Parameter Error

        401:
          description: Unauthorized

        404:
          description: Not Found

  /order:
    get:
      summary: Get all my orders
      operationId: order.get
      parameters:
      - name: request
        in: body
        required: true
        schema:
          $ref: '#/definitions/QueryRequest'

      responses:
        200:
          description: "Request was successful"
          schema:
            type: object

        400:
          description: Parameter Error

        401:
          description: Unauthorized

        404:
          description: Not Found

  /trade:
    get:
      summary: Get all my trades
      operationId: trade.get
      parameters:
      - name: request
        in: body
        required: true
        schema:
          $ref: '#/definitions/QueryRequest'

      responses:
        200:
          description: "Request was successful"
          schema:
            type: object

        400:
          description: Parameter Error

        401:
          description: Unauthorized

        404:
          description: Not Found


  /transaction:
    post:
      summary: Place new transaction.
      operationId: transaction.post
      parameters:
      - name: request
        in: body
        required: true
        schema:
          type: object

      responses:
        200:
          description: "Request was successful"
          schema:
            type: object

        400:
          description: Parameter Error

        401:
          description: Unauthorized

        404:
          description: Not Found

    get:
      summary: Get all my transactions
      operationId: transaction.get
      parameters:
      - name: request
        in: body
        required: true
        schema:
          $ref: '#/definitions/QueryRequest'

      responses:
        200:
          description: "Request was successful"
          schema:
            type: object

        400:
          description: Parameter Error

        401:
          description: Unauthorized

        404:
          description: Not Found


  /klines:
    get:
      summary: Get Kline/candlestick bars for a asset pair
      operationId: klines.post
      parameters:
      - name: request
        in: body
        required: true
        schema:
          $ref: '#/definitions/KlinesRequest'

      responses:
        200:
          description: "Request was successful"
          schema:
            type: object
            items:
              $ref: '#/definitions/KlinesResponse'
        400:
          description: Parameter Error

        401:
          description: Unauthorized

        404:
          description: Not Found

  /orderBook:
    get:
      summary: Get order book for a asset pair
      operationId: orderBook.get
      parameters:
      - name: request
        in: body
        required: true
        schema:
          $ref: '#/definitions/OrderBookRequest'

      responses:
        200:
          description: "Request was successful"
          schema:
            type: object
            items:
              $ref: '#/definitions/OrderBookResponse'
        400:
          description: Parameter Error

        401:
          description: Unauthorized

        404:
          description: Not Found

definitions:
  Position:
    type: object
    properties:
      asset:
        type: string
      quantity:
        type: number
        format: double

  QueryRequest:
    type: object
    properties:
      accountId:
        type: string
      accountName:
        type: string


  KlinesInterval:
    type: string
    enum:
    - "1m"
    - "3m"
    - "5m"
    - "15m"
    - "30m"
    - "1h"
    - "2h"
    - "4h"
    - "6h"
    - "8h"
    - "12h"
    - "1d"
    - "3d"
    - "1w"
    - "1M"

  KlinesRequest:
    type: object
    properties:
      assetPair:
        type: string
      interval:
        $ref: '#/definitions/KlinesInterval'
      startTime:
        type: integer
        format: int64
      endTime:
        type: integer
        format: int64
      limit:
        type: integer

  KlinesResponse:
    type: array
    items:
      type: array
      items:
        type: object

  OrderBookRequest:
    type: object
    properties:
      assetPair:
        type: string
      limit:
        type: integer

  OrderBookResponse:
    type: object
    properties:
      bids:
        type: object
        items:
          type: array
          items:
            type: object
      asks:
        type: object
        items:
          type: array
          items:
            type: object




